# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            scumjr
tagline:          '/'
description:      ''
url:              https://scumjr.github.io
baseurl:          /

author:
  name:           'scumjr'
  url:            https://infosec.exchange/@chaos

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scumjr
