# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            scumjr
tagline:          'A Jekyll theme'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'scumjr'
  url:            https://twitter.com/scumjr_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scumjr
